version: '3'
services:
  api-cliente:
    build:
      context: ./
      dockerfile: ./Dockerfile
  image: cliete/api
  ports:
    - "8080:8080"
    - "5005:5005"
  envirioment:
    - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx200m -Xms128m -XX:MaxMetaspaceSize=128m
    - PROFILE