services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ../dados:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  db:
    image: postgres
    container_name: postgres
    ports:
      - 16432:5432
    environment:
      POSTGRES_DB: nota_fiscal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234